version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 927801033080.dkr.ecr.us-east-1.amazonaws.com
  
  post_build:
    commands:
      - docker tag webapprepo:latest 927801033080.dkr.ecr.us-east-1.amazonaws.com/webapprepo:latest
      - docker push 927801033080.dkr.ecr.us-east-1.amazonaws.com/webapprepo:latest
